In [3]:
import pandas as pd

In [4]:
import os
print(os.getcwd())

C:\Users\ASUS\Downloads\Insider_Threat_Detection_Project\notebooks

In [5]:
logon_data = pd.read_csv("../dataset/logon.csv")

In [6]:
logon_data.head()

                         id                 date     user       pc activity
0  {X1D9-S0ES98JV-5357PWMI}  01/02/2010 06:49:00  NGF0157  PC-6056    Logon
1  {G2B3-L6EJ61GT-2222RKSO}  01/02/2010 06:50:00  LRR0148  PC-4275    Logon
2  {U6Q3-U0WE70UA-3770UREL}  01/02/2010 06:53:04  LRR0148  PC-4124    Logon
3  {I0N5-R7NA26TG-6263KNGM}  01/02/2010 07:00:00  IRM0931  PC-7188    Logon
4  {D1S0-N6FH62BT-5398KANK}  01/02/2010 07:00:00  MOH0273  PC-6699    Logon

In [7]:
logon_data.shape

(854859, 5)

In [8]:
logon_data.columns

Index(['id', 'date', 'user', 'pc', 'activity'], dtype='object')

In [9]:
logon_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 854859 entries, 0 to 854858
Data columns (total 5 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        854859 non-null  object
 1   date      854859 non-null  object
 2   user      854859 non-null  object
 3   pc        854859 non-null  object
 4   activity  854859 non-null  object
dtypes: object(5)
memory usage: 32.6+ MB

In [10]:
logon_data.isnull().sum()

id          0
date        0
user        0
pc          0
activity    0
dtype: int64

In [11]:
logon_data.head()

                         id                 date     user       pc activity
0  {X1D9-S0ES98JV-5357PWMI}  01/02/2010 06:49:00  NGF0157  PC-6056    Logon
1  {G2B3-L6EJ61GT-2222RKSO}  01/02/2010 06:50:00  LRR0148  PC-4275    Logon
2  {U6Q3-U0WE70UA-3770UREL}  01/02/2010 06:53:04  LRR0148  PC-4124    Logon
3  {I0N5-R7NA26TG-6263KNGM}  01/02/2010 07:00:00  IRM0931  PC-7188    Logon
4  {D1S0-N6FH62BT-5398KANK}  01/02/2010 07:00:00  MOH0273  PC-6699    Logon

In [12]:
device_data = pd.read_csv("../dataset/device.csv")
email_data = pd.read_csv("../dataset/email.csv")
file_data = pd.read_csv("../dataset/file.csv")
psychometric_data = pd.read_csv("../dataset/psychometric.csv")

In [13]:
print(device_data.shape)
print(email_data.shape)
print(file_data.shape)
print(psychometric_data.shape)

(405380, 5)
(2629979, 11)
(445581, 6)
(1000, 7)

In [14]:
logon_data['date'] = pd.to_datetime(logon_data['date'])
device_data['date'] = pd.to_datetime(device_data['date'])
email_data['date'] = pd.to_datetime(email_data['date'])
file_data['date'] = pd.to_datetime(file_data['date'])

In [15]:
print(logon_data.dtypes)

id                  object
date        datetime64[ns]
user                object
pc                  object
activity            object
dtype: object